ARG NODE_VERSION=21.6.2

FROM node:${NODE_VERSION}-alpine AS base

WORKDIR /app
COPY package*.json ./
COPY prisma ./prisma 

RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3000
ENV PORT 3000
CMD npm run dev